name: "Code check"

on:
  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"
      - "artisan"

concurrency:
  group: larastrict-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@277edc3ba14b1723502b5455cc95aacf0f7c196f
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@277edc3ba14b1723502b5455cc95aacf0f7c196f
    with:
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

