name: Check pull requests

on:
  pull_request:
    branches: [ main ]

jobs:
  commits:
    name: 👮‍Confronts to conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.5
